sudo: false

language: node_js
node_js:
  - "10.8.0"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install -g gatsby-cli
  - npm install -g yarn

script:
  - gatsby build
