sudo: false

language: node_js
node_js:
  - "10.8.0"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install -g gatsby-cli
  - npm install -g yarn

jobs:
  include:
    - stage: Build
      install: yarn install
      script: gatsby build
    - stage: Lighthouse
      if: type = pull_request
      install: yarn install
      script: echo $TRAVIS_REPO_SLUG $TRAVIS_PULL_REQUEST_SHA
