sudo: false

language: node_js
node_js:
  - "10.8.0"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install -g gatsby-cli

jobs:
  include:
    - stage: Build
      install: yarn install --frozen-lockfile
      script: gatsby build

after_success:
  - yarn run lh --perf 80 --pwa 80 --a11y 80 --bp 80 --seo 80 "$(wait-for-netlify-preview)"
