#==============================
# General site config
#==============================

name: "Daniel T. Eden, Designer"
description: Designer
url: http://daneden.me

markdown: kramdown

color:
  - "#c64f51" # Fall
  - "#a881a2" # Winter
  - "#4fb5c6" # Spring
  - "#fcb500" # Summer

highlighter: true

permalink: pretty


#==============================
# File inclusions/exclusions
#==============================

include: [".htaccess"]


#==============================
# Plugins
#==============================

assets:
  js_compressor: uglifier
  css_compressor: sass
  cache: true
  sources:
    - _assets/scss
    - _assets/js
  cachebust: hard
