#==============================
# General site config
#==============================

name: "Daniel T. Eden, Designer"
description: Designer
url: http://daneden.me

markdown: kramdown

color: "#FCB500"

highlighter: true

permalink: pretty


#==============================
# File inclusions/exclusions
#==============================

include: [".htaccess"]


#==============================
# Plugins
#==============================

assets:
  js_compressor: uglifier
  css_compressor: sass
  cache: true
  sources:
    - _assets/scss
    - _assets/js
  cachebust: hard
