#==============================
# General site config
#==============================

name: "Daniel Eden, Designer"
description: The website and blog of Daniel Eden, Designer.
url: https://daneden.me

plugins: [jekyll-typogrify, jekyll-assets]

markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "fenced_code_blocks", "footnotes", "highlight"]

color:
  - "#00C266"

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true

#==============================
# File inclusions/exclusions
#==============================

include: [".htaccess"]
exclude: ["node_modules", "gulpfile.js", "Gemfile", "Gemfile.lock", "package.json", "scripts"]


#==============================
# Plugins
#==============================

assets:
  digest: true
  sources:
    - "_assets/css"
    - "_assets/js"
    - "uploads"
