name: "Daniel T. Eden, Designer"
description: Designer
url: https://daneden.me

gems:
- jekyll-sitemap

markdown: kramdown

color: "#a881a2"

highlighter: true

permalink: pretty

include: [".htaccess"]
exclude: ["vendor", "node_modules", "package.json", "Gruntfile.js"]

assets:
  js_compressor: uglifier
  css_compressor: sass
  cache: true
  sources:
    - _assets/scss
    - _assets/js
  cachebust: hard

picture:
  source: _uploads
  output: uploads
  markup: "picture"
  presets:
    default:
      ppi: [1]
      source_default:
        width: "480"
      source_600:
        width: "630"
        media: "(min-width: 620px)"
      source_960:
        width: "1350"
        media: "(min-width: 900px)"
