name: "Daniel T. Eden, Designer"
description: Designer
url: https://daneden.me

gems:
- jekyll-sitemap

markdown: kramdown

highlighter: true

permalink: pretty

include: [".htaccess"]
exclude: ["node_modules", "package.json", "Gruntfile.js"]

assets:
  css_compressor: sass
  cache: true
  sources:
    - _assets/scss
    - _assets/js
  cachebust: hard
