version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.7.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: yarn test

      - run:
          name: Build Site
          command: yarn build

      - run:
          name: Setting Up Lighthouse
          command: sudo npm install -g wait-for-netlify-preview

      - run:
          name: Run Lighthouse Performance Tests
          command: yarn run lh --perf 80 --pwa 80 --a11y 80 --bp 80 --seo 80 "$(wait-for-netlify-preview)"
